knp_snappy:
    pdf:
        enabled:    true
        binary:     '"%env(WKHTMLTOPDF_PATH)%\wkhtmltopdf"'
        options:    []
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
